


// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// ==============================================
// This file is autogenerated
// ==============================================

namespace Microsoft.Diagnostics.Instrumentation.Extensions.Base
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// This type is generic to avoid problems merging it to mscorlib
    /// </summary>
    /// <typeparam name="T">This generic attribute has no purpose</typeparam>

    internal class ECB<T>
    {
            internal static Dictionary<int, Func<object, object, object>>
                callbacks0 = new Dictionary<int, Func<object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object>>
                callbacks1 = new Dictionary<int, Func<object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object>>
                callbacks2 = new Dictionary<int, Func<object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object>>
                callbacks3 = new Dictionary<int, Func<object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object>>
                callbacks4 = new Dictionary<int, Func<object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object>>
                callbacks5 = new Dictionary<int, Func<object, object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object, object>>
                callbacks6 = new Dictionary<int, Func<object, object, object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object>>
                callbacks7 = new Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object>>
                callbacks8 = new Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object>>
                callbacks9 = new Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object>>
                callbacks10 = new Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object>>
                callbacks11 = new Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object, object>>
                callbacks12 = new Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object, object, object>>
                callbacks13 = new Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object, object, object>>();
            internal static Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object, object, object, object>>
                callbacks14 = new Dictionary<int, Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object, object, object, object>>();
    }

}

// Underscore _System assembly will be treated as regular System namespace by ImportModule function of Instrumentation Engine.
// This is done to avoid conflicts during compilation
namespace _System.Diagnostics
{
    using Microsoft.Diagnostics.Instrumentation.Extensions.Base;
    using System;

    /// <summary>
    /// This class defines public contract to register new callbacks
    /// </summary>
    public partial class DebuggerHiddenAttribute : Attribute
    {

        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue)
        {
            Func<object, object, object> func = null;
            if (ECB<int>.callbacks0.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0)
        {
            Func<object, object, object, object> func = null;
            if (ECB<int>.callbacks1.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1)
        {
            Func<object, object, object, object, object> func = null;
            if (ECB<int>.callbacks2.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2)
        {
            Func<object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks3.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3)
        {
            Func<object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks4.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4)
        {
            Func<object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks5.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
        {
            Func<object, object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks6.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4, arg5);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
        {
            Func<object, object, object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks7.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7)
        {
            Func<object, object, object, object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks8.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8)
        {
            Func<object, object, object, object, object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks9.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9)
        {
            Func<object, object, object, object, object, object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks10.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10)
        {
            Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks11.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11)
        {
            Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks12.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12)
        {
            Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks13.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            else
                return returnValue;
        }
        public static object ApplicationInsights_OnEnd(int methodId, object context, object returnValue, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9, object arg10, object arg11, object arg12, object arg13)
        {
            Func<object, object, object, object, object, object, object, object, object, object, object, object, object, object, object, object, object> func = null;
            if (ECB<int>.callbacks14.TryGetValue(methodId, out func) && (func != null))
                return func(context, returnValue, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            else
                return returnValue;
        }
    }
}

