# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "microsoft/clr-instrumentation-engine-owners"
    target-branch: "main"