# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "microsoft/clr-instrumentation-engine-owners"
    target-branch: "main"


  - package-ecosystem: nuget
    directory: /src/Dependencies
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Extensions.Base.Api.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Extensions.Base.Api
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/InstrumentationEngine.Attach
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/InstrumentationEngine.Installer.NuGet/Module
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/InstrumentationEngine.NuGet.Headers
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/InstrumentationEngine.NuGet
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/InstrumentationEngine.SiteExtension
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/InstrumentationEngine.XdtExtensions
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Tests/InstrEngineTests/InstrEngineTests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Tests/InstrEngineTests/TestAppRunner
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Tests/RemoteUnitTestExecutor.Host
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Tests/RemoteUnitTestExecutor
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/unix/dependencies
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/unix/docker/dockerfiles/build/alpine
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/unix/docker/dockerfiles/build/ubuntu
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/ApplicationInsightsCompatibility/Intercept.2.0.1.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/ApplicationInsightsCompatibility/Intercept.Latest.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/RawProfilerHook/RawProfilerHook.Tests
    schedule:
      interval: daily
