// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#ifndef OPDEF
#error Define OPDEF(xxx) before including this header
#endif


#define Pop0 0
#define Pop1 1
#define PopI 1
#define PopI8 1
#define PopR 1
#define PopR8 1
#define PopR4 1
#define PopRef 1
#define VarPop -1

#define Push0 0
#define Push1 1
#define PushI 1
#define PushI8 1
#define PushR 1
#define PushR8 1
#define PushR4 1
#define PushRef 1
#define VarPush -1


//                                                                Operand Operand                Alternate      Opcode       Stack       Stack
//    Ordinal  Code                   Name                Length  Length  Type                   Opcode         Flags        Pops        Pushes
//    -------- ---------------------  ------------------- ------- ------- ---------------------- ------------   ---------    ---------   ---------
OPDEF(0x0000, Cee_Nop, _T("nop"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop0,               Push0)
OPDEF(0x0001, Cee_Break, _T("break"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                       Pop0,               Push0)
OPDEF(0x0002, Cee_Ldarg_0, _T("ldarg.0"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               Push1)
OPDEF(0x0003, Cee_Ldarg_1, _T("ldarg.1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               Push1)
OPDEF(0x0004, Cee_Ldarg_2, _T("ldarg.2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               Push1)
OPDEF(0x0005, Cee_Ldarg_3, _T("ldarg.3"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               Push1)
OPDEF(0x0006, Cee_Ldloc_0, _T("ldloc.0"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               Push1)
OPDEF(0x0007, Cee_Ldloc_1, _T("ldloc.1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               Push1)
OPDEF(0x0008, Cee_Ldloc_2, _T("ldloc.2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               Push1)
OPDEF(0x0009, Cee_Ldloc_3, _T("ldloc.3"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               Push1)
OPDEF(0x000A, Cee_Stloc_0, _T("stloc.0"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               Push0)
OPDEF(0x000B, Cee_Stloc_1, _T("stloc.1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               Push0)
OPDEF(0x000C, Cee_Stloc_2, _T("stloc.2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               Push0)
OPDEF(0x000D, Cee_Stloc_3, _T("stloc.3"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               Push0)
OPDEF(0x000E, Cee_Ldarg_S, _T("ldarg.s"), 1, 1, ILOperandType_Byte, Cee_Ldarg, ILOpcodeFlag_None,                     Pop0,               Push1)
OPDEF(0x000F, Cee_Ldarga_S, _T("ldarga.s"), 1, 1, ILOperandType_Byte, Cee_Ldarga, ILOpcodeFlag_None,                  Pop0,               PushI)
OPDEF(0x0010, Cee_Starg_S, _T("starg.s"), 1, 1, ILOperandType_Byte, Cee_Starg, ILOpcodeFlag_None,                     Pop1,               Push0)
OPDEF(0x0011, Cee_Ldloc_S, _T("ldloc.s"), 1, 1, ILOperandType_Byte, Cee_Ldloc, ILOpcodeFlag_None,                     Pop0,               Push1)
OPDEF(0x0012, Cee_Ldloca_S, _T("ldloca.s"), 1, 1, ILOperandType_Byte, Cee_Ldloca, ILOpcodeFlag_None,                  Pop0,               PushI)
OPDEF(0x0013, Cee_Stloc_S, _T("stloc.s"), 1, 1, ILOperandType_Byte, Cee_Stloc, ILOpcodeFlag_None,                     Pop1,               Push0)
OPDEF(0x0014, Cee_Ldnull, _T("ldnull"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                     Pop0,               PushRef)
OPDEF(0x0015, Cee_Ldc_I4_M1, _T("ldc.i4.m1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               Pop0,               PushI)
OPDEF(0x0016, Cee_Ldc_I4_0, _T("ldc.i4.0"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop0,               PushI)
OPDEF(0x0017, Cee_Ldc_I4_1, _T("ldc.i4.1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop0,               PushI)
OPDEF(0x0018, Cee_Ldc_I4_2, _T("ldc.i4.2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop0,               PushI)
OPDEF(0x0019, Cee_Ldc_I4_3, _T("ldc.i4.3"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop0,               PushI)
OPDEF(0x001A, Cee_Ldc_I4_4, _T("ldc.i4.4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop0,               PushI)
OPDEF(0x001B, Cee_Ldc_I4_5, _T("ldc.i4.5"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop0,               PushI)
OPDEF(0x001C, Cee_Ldc_I4_6, _T("ldc.i4.6"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop0,               PushI)
OPDEF(0x001D, Cee_Ldc_I4_7, _T("ldc.i4.7"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop0,               PushI)
OPDEF(0x001E, Cee_Ldc_I4_8, _T("ldc.i4.8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop0,               PushI)
OPDEF(0x001F, Cee_Ldc_I4_S, _T("ldc.i4.s"), 1, 1, ILOperandType_Byte, Cee_Ldc_I4, ILOpcodeFlag_None,                  Pop0,               PushI)
OPDEF(0x0020, Cee_Ldc_I4, _T("ldc.i4"), 1, 4, ILOperandType_Int, Cee_Ldc_I4_S, ILOpcodeFlag_None,                     Pop0,               PushI)
OPDEF(0x0021, Cee_Ldc_I8, _T("ldc.i8"), 1, 8, ILOperandType_Long, Cee_Invalid, ILOpcodeFlag_None,                     Pop0,               PushI8)
OPDEF(0x0022, Cee_Ldc_R4, _T("ldc.r4"), 1, 4, ILOperandType_Single, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               PushR4)
OPDEF(0x0023, Cee_Ldc_R8, _T("ldc.r8"), 1, 8, ILOperandType_Double, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               PushR8)
OPDEF(0x0024, Cee_Unused49, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x0025, Cee_Dup, _T("dup"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1,               Push1+Push1)
OPDEF(0x0026, Cee_Pop, _T("pop"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1,               Push0)
OPDEF(0x0027, Cee_Jmp, _T("jmp"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                          Pop0,               Push0)
OPDEF(0x0028, Cee_Call, _T("call"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                        VarPop,             VarPush)
OPDEF(0x0029, Cee_Calli, _T("calli"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                      VarPop,             VarPush)
OPDEF(0x002A, Cee_Ret, _T("ret"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           VarPop,             Push0)
OPDEF(0x002B, Cee_Br_S, _T("br.s"), 1, 1, ILOperandType_Byte, Cee_Br, ILOpcodeFlag_Branch,                            Pop0,               Push0)
OPDEF(0x002C, Cee_Brfalse_S, _T("brfalse.s"), 1, 1, ILOperandType_Byte, Cee_Brfalse, ILOpcodeFlag_Branch,             PopI,               Push0)
OPDEF(0x002D, Cee_Brtrue_S, _T("brtrue.s"), 1, 1, ILOperandType_Byte, Cee_Brtrue, ILOpcodeFlag_Branch,                PopI,               Push0)
OPDEF(0x002E, Cee_Beq_S, _T("beq.s"), 1, 1, ILOperandType_Byte, Cee_Beq, ILOpcodeFlag_Branch,                         Pop1+Pop1,          Push0)
OPDEF(0x002F, Cee_Bge_S, _T("bge.s"), 1, 1, ILOperandType_Byte, Cee_Bge, ILOpcodeFlag_Branch,                         Pop1+Pop1,          Push0)
OPDEF(0x0030, Cee_Bgt_S, _T("bgt.s"), 1, 1, ILOperandType_Byte, Cee_Bgt, ILOpcodeFlag_Branch,                         Pop1+Pop1,          Push0)
OPDEF(0x0031, Cee_Ble_S, _T("ble.s"), 1, 1, ILOperandType_Byte, Cee_Ble, ILOpcodeFlag_Branch,                         Pop1+Pop1,          Push0)
OPDEF(0x0032, Cee_Blt_S, _T("blt.s"), 1, 1, ILOperandType_Byte, Cee_Blt, ILOpcodeFlag_Branch,                         Pop1+Pop1,          Push0)
OPDEF(0x0033, Cee_Bne_Un_S, _T("bne.un.s"), 1, 1, ILOperandType_Byte, Cee_Bne_Un, ILOpcodeFlag_Branch,                Pop1+Pop1,          Push0)
OPDEF(0x0034, Cee_Bge_Un_S, _T("bge.un.s"), 1, 1, ILOperandType_Byte, Cee_Bge_Un, ILOpcodeFlag_Branch,                Pop1+Pop1,          Push0)
OPDEF(0x0035, Cee_Bgt_Un_S, _T("bgt.un.s"), 1, 1, ILOperandType_Byte, Cee_Bgt_Un, ILOpcodeFlag_Branch,                Pop1+Pop1,          Push0)
OPDEF(0x0036, Cee_Ble_Un_S, _T("ble.un.s"), 1, 1, ILOperandType_Byte, Cee_Ble_Un, ILOpcodeFlag_Branch,                Pop1+Pop1,          Push0)
OPDEF(0x0037, Cee_Blt_Un_S, _T("blt.un.s"), 1, 1, ILOperandType_Byte, Cee_Blt_Un, ILOpcodeFlag_Branch,                Pop1+Pop1,          Push0)
OPDEF(0x0038, Cee_Br, _T("br"), 1, 4, ILOperandType_Int, Cee_Br_S, ILOpcodeFlag_Branch,                               Pop0,               Push0)
OPDEF(0x0039, Cee_Brfalse, _T("brfalse"), 1, 4, ILOperandType_Int, Cee_Brfalse_S, ILOpcodeFlag_Branch,                PopI,               Push0)
OPDEF(0x003A, Cee_Brtrue, _T("brtrue"), 1, 4, ILOperandType_Int, Cee_Brtrue_S, ILOpcodeFlag_Branch,                   PopI,               Push0)
OPDEF(0x003B, Cee_Beq, _T("beq"), 1, 4, ILOperandType_Int, Cee_Beq_S, ILOpcodeFlag_Branch,                            Pop1+Pop1,          Push0)
OPDEF(0x003C, Cee_Bge, _T("bge"), 1, 4, ILOperandType_Int, Cee_Bge_S, ILOpcodeFlag_Branch,                            Pop1+Pop1,          Push0)
OPDEF(0x003D, Cee_Bgt, _T("bgt"), 1, 4, ILOperandType_Int, Cee_Bgt_S, ILOpcodeFlag_Branch,                            Pop1+Pop1,          Push0)
OPDEF(0x003E, Cee_Ble, _T("ble"), 1, 4, ILOperandType_Int, Cee_Ble_S, ILOpcodeFlag_Branch,                            Pop1+Pop1,          Push0)
OPDEF(0x003F, Cee_Blt, _T("blt"), 1, 4, ILOperandType_Int, Cee_Blt_S, ILOpcodeFlag_Branch,                            Pop1+Pop1,          Push0)
OPDEF(0x0040, Cee_Bne_Un, _T("bne.un"), 1, 4, ILOperandType_Int, Cee_Bne_Un_S, ILOpcodeFlag_Branch,                   Pop1+Pop1,          Push0)
OPDEF(0x0041, Cee_Bge_Un, _T("bge.un"), 1, 4, ILOperandType_Int, Cee_Bge_Un_S, ILOpcodeFlag_Branch,                   Pop1+Pop1,          Push0)
OPDEF(0x0042, Cee_Bgt_Un, _T("bgt.un"), 1, 4, ILOperandType_Int, Cee_Bgt_Un_S, ILOpcodeFlag_Branch,                   Pop1+Pop1,          Push0)
OPDEF(0x0043, Cee_Ble_Un, _T("ble.un"), 1, 4, ILOperandType_Int, Cee_Ble_Un_S, ILOpcodeFlag_Branch,                   Pop1+Pop1,          Push0)
OPDEF(0x0044, Cee_Blt_Un, _T("blt.un"), 1, 4, ILOperandType_Int, Cee_Blt_Un_S, ILOpcodeFlag_Branch,                   Pop1+Pop1,          Push0)
OPDEF(0x0045, Cee_Switch, _T("switch"), 1, -1, ILOperandType_Switch, Cee_Invalid, ILOpcodeFlag_None,                  PopI,               Push0)
OPDEF(0x0046, Cee_Ldind_I1, _T("ldind.i1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushI)
OPDEF(0x0047, Cee_Ldind_U1, _T("ldind.u1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushI)
OPDEF(0x0048, Cee_Ldind_I2, _T("ldind.i2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushI)
OPDEF(0x0049, Cee_Ldind_U2, _T("ldind.u2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushI)
OPDEF(0x004A, Cee_Ldind_I4, _T("ldind.i4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushI)
OPDEF(0x004B, Cee_Ldind_U4, _T("ldind.u4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushI)
OPDEF(0x004C, Cee_Ldind_I8, _T("ldind.i8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushI8)
OPDEF(0x004D, Cee_Ldind_I, _T("ldind.i"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   PopI,               PushI)
OPDEF(0x004E, Cee_Ldind_R4, _T("ldind.r4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushR4)
OPDEF(0x004F, Cee_Ldind_R8, _T("ldind.r8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushR8)
OPDEF(0x0050, Cee_Ldind_Ref, _T("ldind.ref"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopI,               PushRef)
OPDEF(0x0051, Cee_Stind_Ref, _T("stind.ref"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopI+PopI,          Push0)
OPDEF(0x0052, Cee_Stind_I1, _T("stind.i1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI+PopI,          Push0)
OPDEF(0x0053, Cee_Stind_I2, _T("stind.i2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI+PopI,          Push0)
OPDEF(0x0054, Cee_Stind_I4, _T("stind.i4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI+PopI,          Push0)
OPDEF(0x0055, Cee_Stind_I8, _T("stind.i8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI+PopI8,         Push0)
OPDEF(0x0056, Cee_Stind_R4, _T("stind.r4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI+PopR4,         Push0)
OPDEF(0x0057, Cee_Stind_R8, _T("stind.r8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI+PopR8,         Push0)
OPDEF(0x0058, Cee_Add, _T("add"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          Push1)
OPDEF(0x0059, Cee_Sub, _T("sub"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          Push1)
OPDEF(0x005A, Cee_Mul, _T("mul"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          Push1)
OPDEF(0x005B, Cee_Div, _T("div"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          Push1)
OPDEF(0x005C, Cee_Div_Un, _T("div.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                     Pop1+Pop1,          Push1)
OPDEF(0x005D, Cee_Rem, _T("rem"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          Push1)
OPDEF(0x005E, Cee_Rem_Un, _T("rem.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                     Pop1+Pop1,          Push1)
OPDEF(0x005F, Cee_And, _T("and"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          Push1)
OPDEF(0x0060, Cee_Or, _T("or"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                             Pop1+Pop1,          Push1)
OPDEF(0x0061, Cee_Xor, _T("xor"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          Push1)
OPDEF(0x0062, Cee_Shl, _T("shl"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          Push1)
OPDEF(0x0063, Cee_Shr, _T("shr"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          Push1)
OPDEF(0x0064, Cee_Shr_Un, _T("shr.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                     Pop1+Pop1,          Push1)
OPDEF(0x0065, Cee_Neg, _T("neg"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1,               Push1)
OPDEF(0x0066, Cee_Not, _T("not"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1,               Push1)
OPDEF(0x0067, Cee_Conv_I1, _T("conv.i1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushI)
OPDEF(0x0068, Cee_Conv_I2, _T("conv.i2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushI)
OPDEF(0x0069, Cee_Conv_I4, _T("conv.i4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushI)
OPDEF(0x006A, Cee_Conv_I8, _T("conv.i8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushI8)
OPDEF(0x006B, Cee_Conv_R4, _T("conv.r4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushR4)
OPDEF(0x006C, Cee_Conv_R8, _T("conv.r8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushR8)
OPDEF(0x006D, Cee_Conv_U4, _T("conv.u4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushI)
OPDEF(0x006E, Cee_Conv_U8, _T("conv.u8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushI8)
OPDEF(0x006F, Cee_Callvirt, _T("callvirt"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                VarPop,             VarPush)
OPDEF(0x0070, Cee_Cpobj, _T("cpobj"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                      PopI+PopI,          Push0)
OPDEF(0x0071, Cee_Ldobj, _T("ldobj"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                      PopI,               Push1)
OPDEF(0x0072, Cee_Ldstr, _T("ldstr"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                      Pop0,               PushRef)
OPDEF(0x0073, Cee_Newobj, _T("newobj"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                    VarPop,             PushRef)
OPDEF(0x0074, Cee_Castclass, _T("castclass"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,              PopRef,             PushRef)
OPDEF(0x0075, Cee_Isinst, _T("isinst"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                    PopRef,             PushI)
OPDEF(0x0076, Cee_Conv_R_Un, _T("conv.r.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               Pop1,               PushR8)
OPDEF(0x0077, Cee_Unused58, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x0078, Cee_Unused1, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                  Pop0,               Push0)
OPDEF(0x0079, Cee_Unbox, _T("unbox"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                      PopRef,             PushI)
OPDEF(0x007A, Cee_Throw, _T("throw"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                       PopRef,             Push0)
OPDEF(0x007B, Cee_Ldfld, _T("ldfld"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                      PopRef,             Push1)
OPDEF(0x007C, Cee_Ldflda, _T("ldflda"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                    PopRef,             PushI)
OPDEF(0x007D, Cee_Stfld, _T("stfld"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                      PopRef+Pop1,        Push0)
OPDEF(0x007E, Cee_Ldsfld, _T("ldsfld"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                    Pop0,               Push1)
OPDEF(0x007F, Cee_Ldsflda, _T("ldsflda"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                  Pop0,               PushI)
OPDEF(0x0080, Cee_Stsfld, _T("stsfld"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                    Pop1,               Push0)
OPDEF(0x0081, Cee_Stobj, _T("stobj"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                      PopI+Pop1,          Push0)
OPDEF(0x0082, Cee_Conv_Ovf_I1_Un, _T("conv.ovf.i1.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,     Pop1,               PushI)
OPDEF(0x0083, Cee_Conv_Ovf_I2_Un, _T("conv.ovf.i2.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,     Pop1,               PushI)
OPDEF(0x0084, Cee_Conv_Ovf_I4_Un, _T("conv.ovf.i4.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,     Pop1,               PushI)
OPDEF(0x0085, Cee_Conv_Ovf_I8_Un, _T("conv.ovf.i8.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,     Pop1,               PushI8)
OPDEF(0x0086, Cee_Conv_Ovf_U1_Un, _T("conv.ovf.u1.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,     Pop1,               PushI)
OPDEF(0x0087, Cee_Conv_Ovf_U2_Un, _T("conv.ovf.u2.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,     Pop1,               PushI)
OPDEF(0x0088, Cee_Conv_Ovf_U4_Un, _T("conv.ovf.u4.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,     Pop1,               PushI)
OPDEF(0x0089, Cee_Conv_Ovf_U8_Un, _T("conv.ovf.u8.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,     Pop1,               PushI8)
OPDEF(0x008A, Cee_Conv_Ovf_I_Un, _T("conv.ovf.i.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,       Pop1,               PushI)
OPDEF(0x008B, Cee_Conv_Ovf_U_Un, _T("conv.ovf.u.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,       Pop1,               PushI)
OPDEF(0x008C, Cee_Box, _T("box"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                          Pop1,               PushRef)
OPDEF(0x008D, Cee_Newarr, _T("newarr"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                    PopI,               PushRef)
OPDEF(0x008E, Cee_Ldlen, _T("ldlen"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                       PopRef,             PushI)
OPDEF(0x008F, Cee_Ldelema, _T("ldelema"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                  PopRef+PopI,        PushI)
OPDEF(0x0090, Cee_Ldelem_I1, _T("ldelem.i1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI,        PushI)
OPDEF(0x0091, Cee_Ldelem_U1, _T("ldelem.u1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI,        PushI)
OPDEF(0x0092, Cee_Ldelem_I2, _T("ldelem.i2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI,        PushI)
OPDEF(0x0093, Cee_Ldelem_U2, _T("ldelem.u2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI,        PushI)
OPDEF(0x0094, Cee_Ldelem_I4, _T("ldelem.i4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI,        PushI)
OPDEF(0x0095, Cee_Ldelem_U4, _T("ldelem.u4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI,        PushI)
OPDEF(0x0096, Cee_Ldelem_I8, _T("ldelem.i8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI,        PushI8)
OPDEF(0x0097, Cee_Ldelem_I, _T("ldelem.i"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopRef+PopI,        PushI)
OPDEF(0x0098, Cee_Ldelem_R4, _T("ldelem.r4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI,        PushR4)
OPDEF(0x0099, Cee_Ldelem_R8, _T("ldelem.r8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI,        PushR8)
OPDEF(0x009A, Cee_Ldelem_Ref, _T("ldelem.ref"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,             PopRef+PopI,        PushRef)
OPDEF(0x009B, Cee_Stelem_I, _T("stelem.i"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopRef+PopI+PopI,   Push0)
OPDEF(0x009C, Cee_Stelem_I1, _T("stelem.i1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI+PopI,   Push0)
OPDEF(0x009D, Cee_Stelem_I2, _T("stelem.i2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI+PopI,   Push0)
OPDEF(0x009E, Cee_Stelem_I4, _T("stelem.i4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI+PopI,   Push0)
OPDEF(0x009F, Cee_Stelem_I8, _T("stelem.i8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI+PopI8,  Push0)
OPDEF(0x00A0, Cee_Stelem_R4, _T("stelem.r4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI+PopR4,  Push0)
OPDEF(0x00A1, Cee_Stelem_R8, _T("stelem.r8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopRef+PopI+PopR8,  Push0)
OPDEF(0x00A2, Cee_Stelem_Ref, _T("stelem.ref"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,             PopRef+PopI+PopRef, Push0)
OPDEF(0x00A3, Cee_Ldelem, _T("ldelem.any"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                PopRef+PopI,        Push1)
OPDEF(0x00A4, Cee_Stelem, _T("stelem.any"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                PopRef+PopI+Pop1,   Push0)
OPDEF(0x00A5, Cee_Unbox_Any, _T("unbox.any"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,              PopRef,             Push1)
OPDEF(0x00A6, Cee_Unused5, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                  Pop0,               Push0)
OPDEF(0x00A7, Cee_Unused6, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                  Pop0,               Push0)
OPDEF(0x00A8, Cee_Unused7, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                  Pop0,               Push0)
OPDEF(0x00A9, Cee_Unused8, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                  Pop0,               Push0)
OPDEF(0x00AA, Cee_Unused9, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                  Pop0,               Push0)
OPDEF(0x00AB, Cee_Unused10, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00AC, Cee_Unused11, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00AD, Cee_Unused12, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00AE, Cee_Unused13, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00AF, Cee_Unused14, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00B0, Cee_Unused15, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00B1, Cee_Unused16, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00B2, Cee_Unused17, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00B3, Cee_Conv_Ovf_I1, _T("conv.ovf.i1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,           Pop1,               PushI)
OPDEF(0x00B4, Cee_Conv_Ovf_U1, _T("conv.ovf.u1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,           Pop1,               PushI)
OPDEF(0x00B5, Cee_Conv_Ovf_I2, _T("conv.ovf.i2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,           Pop1,               PushI)
OPDEF(0x00B6, Cee_Conv_Ovf_U2, _T("conv.ovf.u2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,           Pop1,               PushI)
OPDEF(0x00B7, Cee_Conv_Ovf_I4, _T("conv.ovf.i4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,           Pop1,               PushI)
OPDEF(0x00B8, Cee_Conv_Ovf_U4, _T("conv.ovf.u4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,           Pop1,               PushI)
OPDEF(0x00B9, Cee_Conv_Ovf_I8, _T("conv.ovf.i8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,           Pop1,               PushI8)
OPDEF(0x00BA, Cee_Conv_Ovf_U8, _T("conv.ovf.u8"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,           Pop1,               PushI8)
OPDEF(0x00BB, Cee_Unused50, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00BC, Cee_Unused18, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00BD, Cee_Unused19, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00BE, Cee_Unused20, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00BF, Cee_Unused21, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00C0, Cee_Unused22, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00C1, Cee_Unused23, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00C2, Cee_Refanyval, _T("refanyval"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,              Pop1,               PushI)
OPDEF(0x00C3, Cee_Ckfinite, _T("ckfinite"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 Pop1,               PushR8)
OPDEF(0x00C4, Cee_Unused24, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00C5, Cee_Unused25, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00C6, Cee_Mkrefany, _T("mkrefany"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                PopI,               Push1)
OPDEF(0x00C7, Cee_Unused59, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00C8, Cee_Unused60, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00C9, Cee_Unused61, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00CA, Cee_Unused62, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00CB, Cee_Unused63, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00CC, Cee_Unused64, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00CD, Cee_Unused65, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00CE, Cee_Unused66, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00CF, Cee_Unused67, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00D0, Cee_Ldtoken, _T("ldtoken"), 1, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                  Pop0,               PushI)
OPDEF(0x00D1, Cee_Conv_U2, _T("conv.u2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushI)
OPDEF(0x00D2, Cee_Conv_U1, _T("conv.u1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1,               PushI)
OPDEF(0x00D3, Cee_Conv_I, _T("conv.i"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                     Pop1,               PushI)
OPDEF(0x00D4, Cee_Conv_Ovf_I, _T("conv.ovf.i"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,             Pop1,               PushI)
OPDEF(0x00D5, Cee_Conv_Ovf_U, _T("conv.ovf.u"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,             Pop1,               PushI)
OPDEF(0x00D6, Cee_Add_Ovf, _T("add.ovf"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1+Pop1,          Push1)
OPDEF(0x00D7, Cee_Add_Ovf_Un, _T("add.ovf.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,             Pop1+Pop1,          Push1)
OPDEF(0x00D8, Cee_Mul_Ovf, _T("mul.ovf"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1+Pop1,          Push1)
OPDEF(0x00D9, Cee_Mul_Ovf_Un, _T("mul.ovf.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,             Pop1+Pop1,          Push1)
OPDEF(0x00DA, Cee_Sub_Ovf, _T("sub.ovf"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop1+Pop1,          Push1)
OPDEF(0x00DB, Cee_Sub_Ovf_Un, _T("sub.ovf.un"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,             Pop1+Pop1,          Push1)
OPDEF(0x00DC, Cee_Endfinally, _T("endfinally"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,             Pop0,               Push0)
OPDEF(0x00DD, Cee_Leave, _T("leave"), 1, 4, ILOperandType_Int, Cee_Leave_S, ILOpcodeFlag_Branch,                      Pop0,               Push0)
OPDEF(0x00DE, Cee_Leave_S, _T("leave.s"), 1, 1, ILOperandType_Byte, Cee_Leave, ILOpcodeFlag_Branch,                   Pop0,               Push0)
OPDEF(0x00DF, Cee_Stind_I, _T("stind.i"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   PopI+PopI,          Push0)
OPDEF(0x00E0, Cee_Conv_U, _T("conv.u"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                     Pop1,               PushI)
OPDEF(0x00E1, Cee_Unused26, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00E2, Cee_Unused27, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00E3, Cee_Unused28, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00E4, Cee_Unused29, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00E5, Cee_Unused30, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00E6, Cee_Unused31, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00E7, Cee_Unused32, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00E8, Cee_Unused33, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00E9, Cee_Unused34, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00EA, Cee_Unused35, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00EB, Cee_Unused36, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00EC, Cee_Unused37, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00ED, Cee_Unused38, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00EE, Cee_Unused39, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00EF, Cee_Unused40, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F0, Cee_Unused41, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F1, Cee_Unused42, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F2, Cee_Unused43, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F3, Cee_Unused44, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F4, Cee_Unused45, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F5, Cee_Unused46, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F6, Cee_Unused47, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F7, Cee_Unused48, _T("unused"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F8, Cee_Prefix7, _T("prefix7"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00F9, Cee_Prefix6, _T("prefix6"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00FA, Cee_Prefix5, _T("prefix5"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00FB, Cee_Prefix4, _T("prefix4"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00FC, Cee_Prefix3, _T("prefix3"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00FD, Cee_Prefix2, _T("prefix2"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00FE, Cee_Prefix1, _T("prefix1"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x00FF, Cee_Prefixref, _T("prefixref"), 1, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,             Pop0,               Push0)
OPDEF(0x0100, Cee_Arglist, _T("arglist"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               PushI)
OPDEF(0x0101, Cee_Ceq, _T("ceq"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          PushI)
OPDEF(0x0102, Cee_Cgt, _T("cgt"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          PushI)
OPDEF(0x0103, Cee_Cgt_Un, _T("cgt.un"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                     Pop1+Pop1,          PushI)
OPDEF(0x0104, Cee_Clt, _T("clt"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                           Pop1+Pop1,          PushI)
OPDEF(0x0105, Cee_Clt_Un, _T("clt.un"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                     Pop1+Pop1,          PushI)
OPDEF(0x0106, Cee_Ldftn, _T("ldftn"), 2, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                      Pop0,               PushI)
OPDEF(0x0107, Cee_Ldvirtftn, _T("ldvirtftn"), 2, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,              PopRef,             PushI)
OPDEF(0x0108, Cee_Unused56, _T("unused"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x0109, Cee_Ldarg, _T("ldarg"), 2, 2, ILOperandType_UShort, Cee_Ldarg_S, ILOpcodeFlag_None,                     Pop0,               Push1)
OPDEF(0x010A, Cee_Ldarga, _T("ldarga"), 2, 2, ILOperandType_UShort, Cee_Ldarga_S, ILOpcodeFlag_None,                  Pop0,               PushI)
OPDEF(0x010B, Cee_Starg, _T("starg"), 2, 2, ILOperandType_UShort, Cee_Starg_S, ILOpcodeFlag_None,                     Pop1,               Push0)
OPDEF(0x010C, Cee_Ldloc, _T("ldloc"), 2, 2, ILOperandType_UShort, Cee_Ldloc_S, ILOpcodeFlag_None,                     Pop0,               Push1)
OPDEF(0x010D, Cee_Ldloca, _T("ldloca"), 2, 2, ILOperandType_UShort, Cee_Ldloca_S, ILOpcodeFlag_None,                  Pop0,               PushI)
OPDEF(0x010E, Cee_Stloc, _T("stloc"), 2, 2, ILOperandType_UShort, Cee_Stloc_S, ILOpcodeFlag_None,                     Pop1,               Push0)
OPDEF(0x010F, Cee_Localloc, _T("localloc"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                 PopI,               PushI)
OPDEF(0x0110, Cee_Unused57, _T("unused"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x0111, Cee_Endfilter, _T("endfilter"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,               PopI,               Push0)
OPDEF(0x0112, Cee_Unaligned, _T("unaligned."), 2, 1, ILOperandType_Byte, Cee_Invalid, ILOpcodeFlag_None,              Pop0,               Push0)
OPDEF(0x0113, Cee_Volatile, _T("volatile."), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                Pop0,               Push0)
OPDEF(0x0114, Cee_Tailcall, _T("tail."), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                    Pop0,               Push0)
OPDEF(0x0115, Cee_Initobj, _T("initobj"), 2, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                  PopI,               Push0)
OPDEF(0x0116, Cee_Constrained, _T("constrained."), 2, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,         Pop0,               Push0)
OPDEF(0x0117, Cee_Cpblk, _T("cpblk"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                       PopI+PopI+PopI,     Push0)
OPDEF(0x0118, Cee_Initblk, _T("initblk"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   PopI+PopI+PopI,     Push0)
OPDEF(0x0119, Cee_Unused69, _T("unused"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x011A, Cee_Rethrow, _T("rethrow"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                   Pop0,               Push0)
OPDEF(0x011B, Cee_Unused51, _T("unused"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x011C, Cee_Sizeof, _T("sizeof"), 2, 4, ILOperandType_Token, Cee_Invalid, ILOpcodeFlag_None,                    Pop0,               PushI)
OPDEF(0x011D, Cee_Refanytype, _T("refanytype"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,             Pop1,               PushI)
OPDEF(0x011E, Cee_Readonly, _T("readonly."), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_None,                Pop0,               Push0)
OPDEF(0x011F, Cee_Unused53, _T("unused"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x0120, Cee_Unused54, _T("unused"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x0121, Cee_Unused55, _T("unused"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x0122, Cee_Unused70, _T("unused"), 2, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Unused,                 Pop0,               Push0)
OPDEF(0x0123, Cee_Count, _T("unused"), 0, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Meta,                      Pop0,               Push0)
OPDEF(0xFFFF, Cee_Invalid, _T("unused"), 0, 0, ILOperandType_None, Cee_Invalid, ILOpcodeFlag_Meta,                    Pop0,               Push0)