//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Microsoft.InstrumentationEngine.EngineConfig {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class InstrumentationEngineConfiguration {
        
        private InstrumentationEngineConfigurationInstrumentationEngine instrumentationEngineField;
        
        private InstrumentationMethodsTypeAddInstrumentationMethod[] instrumentationMethodsField;
        
        /// <remarks/>
        public InstrumentationEngineConfigurationInstrumentationEngine InstrumentationEngine {
            get {
                return this.instrumentationEngineField;
            }
            set {
                this.instrumentationEngineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AddInstrumentationMethod", IsNullable=false)]
        public InstrumentationMethodsTypeAddInstrumentationMethod[] InstrumentationMethods {
            get {
                return this.instrumentationMethodsField;
            }
            set {
                this.instrumentationMethodsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InstrumentationEngineConfigurationInstrumentationEngine {
        
        private SettingsTypeSetting[] settingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable=false)]
        public SettingsTypeSetting[] Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SettingsTypeSetting {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InstrumentationMethodsTypeAddInstrumentationMethod {
        
        private SettingsTypeSetting[] settingsField;
        
        private string methodGuidField;
        
        private string configPathField;
        
        private LoggingFlagsType logLevelField;
        
        private bool logLevelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable=false)]
        public SettingsTypeSetting[] Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MethodGuid {
            get {
                return this.methodGuidField;
            }
            set {
                this.methodGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConfigPath {
            get {
                return this.configPathField;
            }
            set {
                this.configPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LoggingFlagsType LogLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LogLevelSpecified {
            get {
                return this.logLevelFieldSpecified;
            }
            set {
                this.logLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CommonNamespace/CommonTypes")]
    public enum LoggingFlagsType {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Errors = 2,
        
        /// <remarks/>
        Messages = 4,
        
        /// <remarks/>
        Dumps = 8,
    }
}
