//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InstrumentationConfigurationSources {
    
    private InstrumentationConfigurationSourcesInstrumementationConfigurationSource[] instrumementationConfigurationSourceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InstrumementationConfigurationSource")]
    public InstrumentationConfigurationSourcesInstrumementationConfigurationSource[] InstrumementationConfigurationSource {
        get {
            return this.instrumementationConfigurationSourceField;
        }
        set {
            this.instrumementationConfigurationSourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InstrumentationConfigurationSourcesInstrumementationConfigurationSource {
    
    private InstrumentationConfigurationSourcesInstrumementationConfigurationSourcePlatform[] platformsField;
    
    private InstrumentationConfigurationSourcesInstrumementationConfigurationSourceSetting[] settingsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Platform", IsNullable=false)]
    public InstrumentationConfigurationSourcesInstrumementationConfigurationSourcePlatform[] Platforms {
        get {
            return this.platformsField;
        }
        set {
            this.platformsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable=false)]
    public InstrumentationConfigurationSourcesInstrumementationConfigurationSourceSetting[] Settings {
        get {
            return this.settingsField;
        }
        set {
            this.settingsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InstrumentationConfigurationSourcesInstrumementationConfigurationSourcePlatform {
    
    private string chipField;
    
    private string pathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Chip {
        get {
            return this.chipField;
        }
        set {
            this.chipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InstrumentationConfigurationSourcesInstrumementationConfigurationSourceSetting {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
