# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: build

on: [push]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Note OSX isn't officially supported yet, but might be in the future.
        # The build here will help ensure no changes are introduced that
        # would make it difficult.
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: out/packages
        key: nuget

    - run: src/build.sh x64 release

    - name: archive so
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: libInstrumentationEngine.so
        path: out/Linux/bin/x64.Release/ClrInstrumentationEngine/libInstrumentationEngine.so

    - name: archive dylib
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: libInstrumentationEngine.dylib
        path: out/OSX/bin/x64.Release/ClrInstrumentationEngine/libInstrumentationEngine.dylib
